name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Test
        run: 
          npm install 
          npm run test